### PR TITLE
Fix parsing Jisho sentences

### PR DESCRIPTION
**Pull request by artemsmikh**
Fixed a problem when some sentences were parsed and displayed incorrectly.

Example:
screen shot 2017-01-21 at 3 14 32 am

How it should be:
screen shot 2017-01-21 at 3 14 44 am

### CODE REVIEW

**Comment by harumando** [comment]
could you please delete the unnecessary console.log at 248 line? It spams to the output. Also could you please move the `_character_code_is_kana` method to `Utils` class?

**Comment by artemsmikh** [comment]
I don't think it's a good idea to put the method `_character_code_is_kana` into the `Utils` class that is common for all the components because this method is likely won't be used outside of `Jisho` component. Maybe it'll be better to create another class, e.g. `JishoUtils` and place it within the `jisho` directory? What do you think?

**Comment by harumando** [comment]
> because this method is likely won't be used outside of Jisho component

i really doubt that this jisho component is the only place where kana will be processed.
`character_code_is_kana` method has really nothing to do with jisho component or parsing jisho. It just checks if the character you have passed into the method is kana.

**Comment by artemsmikh** [comment]
@harumando 
Okay, if you say so. Here it is.

**Pull request merged**
